name: First Workflow

on:
  push:
    branches:
      - master

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print A Welcome Message
        run: echo "Welcome To Our First GitHub Actions Workflow"
