on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "stating"
        type: choice
        options:
          - stating
          - prouduction
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: echo "Deploying The application ${{ inputs.environment }}"
